### ISSUE TITLE
Undefined variable: end_row

### ISSUE THREAD

**Issue by xitude** [colinbm/sagepayadminapi-php#3]
I'm trying the example for the refunds on a set date.
I'm just getting
`````
Undefined variable: end_row
````

**Comment by xitude** [comment]
Fixed it by adding 
`````
$end_row = 1
`````
before
`````
do {
`````

**Comment by colinbm** [comment]
Interesting. I didn't think that should happen, as the first do loop runs before the while is evaluated. Glad you got it sorted though!
